### Learning Scripts: My Own Examples Created From Scratch
Author: Blake Zenuni, Summer 2019

## Importing Libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

---

### Arrays & Array Splicing

In [5]:
# Arrays Learning Cell: I created this learning cell from scratch to practice the basics of arrays.
array_learn = np.random.rand(3,5)
array_learn

array([[0.45026368, 0.77039632, 0.70973344, 0.60534724, 0.46049754],
       [0.88850947, 0.58914841, 0.34652133, 0.35830657, 0.87551106],
       [0.15055056, 0.69276661, 0.20554073, 0.88974355, 0.28333477]])

==> From the above code and result: numpy generates a ```random array``` -- can be thought of as 3 rows and 5 columns below:')

In [6]:
# Arrays Learning Cell:  I created this learning cell from scratch to practice the basics of array slicing.
array_splice_learn = array_learn[:,1]
array_splice_learn

array([0.77039632, 0.58914841, 0.69276661])

==> Now, the line above performs array splicing: taking all rows (```:```), but keeping the second column (```1```).  
*Note:* consider the starting column as 0.  

*---*



***Key take-away:*** The ```[:, :]``` stands for everything from the beginning to the end just like for lists. The difference is that: 
- the first ```:``` stands for first dimension; 
- the second ```:``` for the second dimension.

In [11]:
# Using numpy to generate a simple array with all zeros zeros:
a = np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# Assigning to a second row:
a[1, :] = 2
a

array([[0., 0., 0.],
       [2., 2., 2.],
       [0., 0., 0.]])

In [16]:
# Assigning to second column:
a[:, 1] = 5 
a

array([[0., 5., 0.],
       [2., 5., 2.],
       [0., 5., 0.]])

In [18]:
# Assigning to all:
a[:] = 9.5
a

array([[9.5, 9.5, 9.5],
       [9.5, 9.5, 9.5],
       [9.5, 9.5, 9.5]])

In [23]:
# some random example:
a = np.random.rand(5,22)
a


array([[0.77655411, 0.64252142, 0.21064318, 0.49196114, 0.23073579,
        0.44426076, 0.94811997, 0.17149906, 0.82005486, 0.51275887,
        0.25422378, 0.71672238, 0.79136025, 0.69469163, 0.23523833,
        0.34859293, 0.80963155, 0.7559314 , 0.17213487, 0.21525235,
        0.88480806, 0.37962731],
       [0.20154711, 0.85810788, 0.86430273, 0.60440396, 0.1212748 ,
        0.858235  , 0.45739626, 0.67623979, 0.56936738, 0.22856182,
        0.24770297, 0.3538948 , 0.08523189, 0.44767197, 0.3123485 ,
        0.72982146, 0.90978973, 0.89082631, 0.28768168, 0.77633859,
        0.47373284, 0.75208125],
       [0.85324364, 0.83717896, 0.98869259, 0.5165235 , 0.98959553,
        0.79193982, 0.08529625, 0.36716487, 0.57099471, 0.21957437,
        0.86470529, 0.0416707 , 0.21736778, 0.3190769 , 0.75008241,
        0.31008745, 0.59301333, 0.83537566, 0.30742659, 0.49455174,
        0.69368009, 0.05855779],
       [0.49864703, 0.16644285, 0.22836004, 0.15042672, 0.65205106,
        0.2091535

In [24]:
# some random example, getting complicated with splicing

b = a[:,6:11]
b

array([[0.94811997, 0.17149906, 0.82005486, 0.51275887, 0.25422378],
       [0.45739626, 0.67623979, 0.56936738, 0.22856182, 0.24770297],
       [0.08529625, 0.36716487, 0.57099471, 0.21957437, 0.86470529],
       [0.76765433, 0.31134716, 0.32392299, 0.86084986, 0.12531005],
       [0.39486132, 0.17141096, 0.68696489, 0.18446025, 0.11800523]])

==> *Result*: So what did the line above do... well, it created a new array from the previous array by => (i) taking all rows, (ii) but skipping the columns 0 through 5, starting on the 6th, *and* (ii) go all the way to last column before 11!

*---*

***Key take-away:*** Numpy uses tuples as indexes. In this case, this is a detailed slice assignement. Here is are some coding tips:

- note: column counter begins at 0 for the fist column in a numpy array (not at 1);
- ```[0]``` ==> means line 0 of your matrix;
- ```[(0,0)]``` ==> means cell at 0,0 of your matrix;
- ```[0:1]``` ==> means lines 0 to 1 excluded of your matrix;
- ```[:1]``` ==> excluding the first value means all lines until line 1 excluded;
- ```[1:]``` ==> excluding the last param mean all lines starting form line 1 included;
- ```[:]``` ==> excluding both means all lines;
- ```[::2]``` ==> #the addition of a second ':' is the sampling. (1 item every 2);
- ```[::]``` ==> exluding it means a sampling of 1;
- ```[:,:]``` ==> simply uses a tuple (a single , represents an empty tuple) instead of an index.

**Further Resources**:  
(1) https://stackoverflow.com/questions/16815928/what-does-mean-on-numpy-arrays/16816142  
(2) https://scipy-lectures.org/intro/numpy/array_object.html

---