### Learning Scripts: My Own Examples Created From Scratch
Author: Blake Zenuni, Summer 2019

## Importing Libraries

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

---

### Arrays & Array Splicing

In [5]:
# Arrays Learning Cell: I created this learning cell from scratch to practice the basics of arrays.
array_learn = np.random.rand(3,5)
array_learn

array([[0.45026368, 0.77039632, 0.70973344, 0.60534724, 0.46049754],
       [0.88850947, 0.58914841, 0.34652133, 0.35830657, 0.87551106],
       [0.15055056, 0.69276661, 0.20554073, 0.88974355, 0.28333477]])

==> From the above code and result: numpy generates a ```random array``` -- can be thought of as 3 rows and 5 columns below:')

In [6]:
# Arrays Learning Cell:  I created this learning cell from scratch to practice the basics of array slicing.
array_splice_learn = array_learn[:,1]
array_splice_learn

array([0.77039632, 0.58914841, 0.69276661])

==> Now, the line above performs array splicing: taking all rows (```:```), but keeping the second column (```1```).  
*Note:* consider the starting column as 0.  

*---*



***Key take-away:*** The ```[:, :]``` stands for everything from the beginning to the end just like for lists. The difference is that: 
- the first ```:``` stands for first dimension; 
- the second ```:``` for the second dimension.

In [11]:
# Using numpy to generate a simple array with all zeros zeros:
a = np.zeros((3, 3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# Assigning to a second row:
a[1, :] = 2
a

array([[0., 0., 0.],
       [2., 2., 2.],
       [0., 0., 0.]])

In [16]:
# Assigning to second column:
a[:, 1] = 5 
a

array([[0., 5., 0.],
       [2., 5., 2.],
       [0., 5., 0.]])

In [18]:
# Assigning to all:
a[:] = 9.5
a

array([[9.5, 9.5, 9.5],
       [9.5, 9.5, 9.5],
       [9.5, 9.5, 9.5]])

*---*

***Key take-away:*** Numpy uses tuples as indexes. In this case, this is a detailed slice assignement. Here is are some coding tips:
- ```[0]``` ==> means line 0 of your matrix
- ```[(0,0)]``` ==> means cell at 0,0 of your matrix
- ```[0:1]``` ==> means lines 0 to 1 excluded of your matrix
- ```[:1]``` ==> excluding the first value means all lines until line 1 excluded
- ```[1:]``` ==> excluding the last param mean all lines starting form line 1 included
- ```[:]``` ==> excluding both means all lines
- ```[::2]``` ==> #the addition of a second ':' is the sampling. (1 item every 2)
- ```[::]``` ==> exluding it means a sampling of 1
- ```[:,:]``` ==> simply uses a tuple (a single , represents an empty tuple) instead of an index.

**Further Resources**:  
(1) https://stackoverflow.com/questions/16815928/what-does-mean-on-numpy-arrays/16816142

---